name: Update Sports Stats

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12 PM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to contents (required to push changes)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install webdriver-manager selenium

      - name: Run MLB Scraper
        run: python scraper_mlb.py

      - name: Run NFL Scraper
        run: python scraper_nfl.py

      - name: Run NBA Scraper
        run: python scraper_nba.py

      - name: Run MLB Rbat+ Scraper
        run: python scraper_mlb_Rbat+.py
      
      - name: Run MLB ERA+ Scraper
        run: python scraper_mlb_ERA+.py

      - name: Run NFL Player Scraper
        run: python scraper_NFL_FantRank.py

      - name: Commit and Push Updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mlb_leader_stats_table.json 
          git add nfl_leader_stats_table.json 
          git add nba_leader_stats_table.json 
          git add MLB_position_player_Rbat+.json 
          git add MLB_pitcher_ERA+.json 
          git add NFL_QB_players.json 
          git add NFL_RB_players.json 
          git add NFL_WR_players.json 
              # Add JSON files
          git commit -m "Automated update: MLB, NBA, NFL stats JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
