name: Update MLB and NFL Stats

on:
  schedule:
    - cron: "0 12 * * *"  # Runs every day at 12 PM UTC
  workflow_dispatch:  # Allows manual execution

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow write access to contents (required to push changes)

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install webdriver-manager selenium

      - name: Run MLB Scraper
        run: python scraper.py

      - name: Run NFL Scraper
        run: python scraper_nfl.py

      - name: Commit and Push Updated JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add mlb_leader_stats_table.json nfl_leader_stats_table.json  # Add both JSON files
          git commit -m "Automated update: MLB and NFL stats JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
